# These config values will be shared by all environments but can be overridden.
common: &common
  client_id: "racecar_lean"

development:
  <<: *common
  brokers:
    - redpanda:19092

test:
  <<: *common
  brokers:
    - redpanda:19092

production:
  <<: *common
  brokers:
    - kafka1.myapp.com:9092
    - kafka2.myapp.com:9092
    - kafka3.myapp.com:9092
